In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk(''):
    for filename in filenames:
        print(os.path.join(dirname, filename))
import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [ ]:
data = pd.read_csv('data_tanaman.csv')
data.head()

In [6]:
classes = data['label'].unique()
classes
numClasses = len(classes)
numClasses

array(['beras', 'jagung', 'buncis', 'kacangmerah', 'kacanggude',
       'kacangngengat', 'kacanghijau', 'gramhitam', 'lentil', 'delima',
       'pisang', 'mangga', 'anggur', 'semangka', 'melon musk', 'apel',
       'jeruk', 'pepaya', 'kelapa', 'katun', 'rami', 'kopi'], dtype=object)

In [8]:
#One Hot Encoded Target
target = pd.get_dummies(data['label'])

#Reading the input
features = data.drop(columns = ['label'])
features

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

In [10]:
# Splitting Data
x_train, x_test, y_train, y_test = train_test_split(features, target, random_state = 42, test_size = 0.2)

In [11]:
# Scaling Data
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [31]:
# Data Dimension
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1760, 7)
(1760, 22)
(440, 7)
(440, 22)


In [34]:
# Model
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(1000, activation = 'relu', input_shape = (7,)),
    tf.keras.layers.Dense(500, activation = 'relu'),
    tf.keras.layers.Dense(numClasses, activation = 'softmax')
])

# Compile
model.compile(
    loss = tf.keras.losses.CategoricalCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(),
    metrics = ['accuracy']
)

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, 1000)              8000      
                                                                 
 dense_11 (Dense)            (None, 500)               500500    
                                                                 
 dense_12 (Dense)            (None, 22)                11022     
                                                                 
Total params: 519,522
Trainable params: 519,522
Non-trainable params: 0
_________________________________________________________________


In [38]:
model.fit(x_train, y_train, epochs = 100, 
          validation_data = (x_test, y_test), batch_size = 32)

Epoch 1/100
55/55 [==============================] - 1s 12ms/step - loss: 0.0313 - accuracy: 0.9864 - val_loss: 0.0879 - val_accuracy: 0.9682
Epoch 2/100
55/55 [==============================] - 1s 11ms/step - loss: 0.0263 - accuracy: 0.9892 - val_loss: 0.0673 - val_accuracy: 0.9773
Epoch 3/100
55/55 [==============================] - 1s 11ms/step - loss: 0.0241 - accuracy: 0.9903 - val_loss: 0.0585 - val_accuracy: 0.9795
Epoch 4/100
55/55 [==============================] - 1s 11ms/step - loss: 0.0542 - accuracy: 0.9801 - val_loss: 0.0886 - val_accuracy: 0.9727
Epoch 5/100
55/55 [==============================] - 1s 11ms/step - loss: 0.0234 - accuracy: 0.9915 - val_loss: 0.0772 - val_accuracy: 0.9727
Epoch 6/100
55/55 [==============================] - 1s 11ms/step - loss: 0.0162 - accuracy: 0.9920 - val_loss: 0.0775 - val_accuracy: 0.9705
Epoch 7/100
55/55 [==============================] - 1s 12ms/step - loss: 0.0201 - accuracy: 0.9903 - val_loss: 0.0829 - val_accuracy: 0.9750
Epoch 

In [36]:
#model.predict(features.iloc[0])
io = features.iloc[0].values

In [37]:
tf.constant(io)

<tf.Tensor: shape=(7,), dtype=float64, numpy=
array([ 90.        ,  42.        ,  43.        ,  20.87974371,
        82.00274423,   6.50298529, 202.9355362 ])>

In [22]:
tf.expand_dims(io, -1)

<tf.Tensor: shape=(7, 1), dtype=float64, numpy=
array([[ 90.        ],
       [ 42.        ],
       [ 43.        ],
       [ 20.87974371],
       [ 82.00274423],
       [  6.50298529],
       [202.9355362 ]])>

In [23]:
model.predict(tf.expand_dims(io, 0))

1/1 [==============================] - 0s 130ms/step


array([[2.4628455e-22, 1.3821735e-08, 9.9999952e-01, 1.6523391e-17,
        3.6949946e-16, 7.0830523e-17, 3.2393898e-13, 2.8637870e-18,
        5.1306148e-10, 1.2750963e-24, 5.3110506e-19, 8.8159849e-30,
        7.4010317e-14, 1.5010242e-09, 1.4394605e-12, 1.5999343e-30,
        3.4962029e-16, 2.2253208e-27, 1.4535266e-07, 3.1753478e-09,
        3.4653209e-07, 2.0597926e-13]], dtype=float32)

In [24]:
classes.sort()
classes

array(['anggur', 'apel', 'beras', 'buncis', 'delima', 'gramhitam',
       'jagung', 'jeruk', 'kacanggude', 'kacanghijau', 'kacangmerah',
       'kacangngengat', 'katun', 'kelapa', 'kopi', 'lentil', 'mangga',
       'melon musk', 'pepaya', 'pisang', 'rami', 'semangka'], dtype=object)

In [ ]:
model.save('research_recom.h5')
model.save('research_recom')

In [ ]:
from pickle import dump
dump(scaler, open('scaler.pkl', 'wb'))

In [ ]:
from pickle import load
scaler = load(open('scaler.pkl', 'rb'))

In [ ]:
import h5py
import json

# Baca file H5
filename = 'research_recom.h5'
h5_file = h5py.File(filename, 'r')

# Ubah objek AttributeManager menjadi kamus
json_data = dict(h5_file.attrs)

# Konversi kamus menjadi JSON
json_data = json.dumps(json_data, indent=4)

# Tulis data JSON ke file
json_filename = 'ini_json.json'
with open(json_filename, 'w') as json_file:
    json_file.write(json_data)
